### ISSUE TITLE
                                                              java.lang.RuntimeException: Unable to start receiver com.onradar.react.RNRadarReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onradar.react.RNRadarEventEmitter.sendEvent(java.lang.String, java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by smartdevdom** [radarlabs/react-native-radar#1]
java.lang.RuntimeException: Unable to start receiver com.onradar.react.RNRadarReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onradar.react.RNRadarEventEmitter.sendEvent(java.lang.String, java.lang.Object)' on a null object reference

**Comment by nickpatrick** [comment]
@smartdevdom Can you share more about how you're registering your receiver? Snippets of code and your Android manifest would help.

**Comment by nickpatrick** [comment]
Looks like `RNRadarReceiver` is trying to emit an event through `RNRadarEventEmitter`, which has not been initialized. I will look into https://facebook.github.io/react-native/docs/headless-js-android.html as a solution.

**Comment by smartdevdom** [comment]
I have one problem NativeModules.RNRadar is undefined

**Comment by nickpatrick** [comment]
@smartdevdom This should be resolved in version `1.0.5`.
