### ISSUE TITLE
Radar.trackonce(). crashes on android app but not in ios and Radar.requestPermission doesn't return a call back and don't ask for prompt[For a better experience..] which toggle the location in android.  

### ISSUE THREAD

**Issue by beingArkReal** [radarlabs/react-native-radar#102]
`
   "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-radar": "^3.0.0-beta.1",
`

**Comment by nickpatrick** [comment]
Hey @beingArkReal, thanks for the suggestion. The crash will be fixed in https://github.com/radarlabs/react-native-radar/pull/105. Closing this in favor of #104.
