### ISSUE TITLE
App crashed while launching the react-native-radar app in Android devices

### ISSUE THREAD

**Issue by arimathi14** [radarlabs/react-native-radar#104]
App crashed while launching the react-native-radar app in Android devices
```
java.lang.NullPointerException: Attempt to invoke interface method 'double com.facebook.react.bridge.ReadableMap.getDouble(java.lang.String)' on a null object reference
	at io.radar.react.RNRadarModule.trackOnce(RNRadarModule.java:159)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
atcom.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:163)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:760)
```

## Steps to reproduce

- Clone the code
- Run yarn run android

      
![download (1)](https://user-images.githubusercontent.com/64394789/81893839-1cf66c00-95cc-11ea-95aa-f7fa275ebee0.png)
![download (2)](https://user-images.githubusercontent.com/64394789/81893841-1e279900-95cc-11ea-852b-62dd300639c8.png)

**Comment by nickpatrick** [comment]
Hi @arimathi14, sorry about this. Are you running your own app or the example app? If you are running your own app, can you share your code?

**Comment by arimathi14** [comment]
I am using and executing this code only https://github.com/radarlabs/react-native-radar

**Comment by amorino** [comment]
I'm having the same error using: Radar.trackOnce(); on Android.

**Comment by nickpatrick** [comment]
Got it. We'll have a fix out for this shortly. Sorry for the hassle!

**Comment by nickpatrick** [comment]
This will be fixed in https://github.com/radarlabs/react-native-radar/pull/105. I will update this issue when the fix is released.

**Comment by nickpatrick** [comment]
Hi, this should be fixed in https://github.com/radarlabs/react-native-radar/releases/tag/3.0.1. Can you give it a try and let me know?

**Comment by amorino** [comment]
Now I got the error "RNRadar.trackOnce got 2 arguments, expected 3". 

I'm using the function like this:

```js
 Radar.trackOnce()
  .then(({ location }) => {
    /// some code
  })
  .catch(e => setError(e));
```

**Comment by nickpatrick** [comment]
@amorino Strange, sorry about that. We'll get another fix up today.

**Comment by nickpatrick** [comment]
Hi, please try https://github.com/radarlabs/react-native-radar/releases/tag/3.0.2.

**Comment by arimathi14** [comment]
The app is not crashed. Thanks
