### ISSUE TITLE
"Limit: The max number of places to return" mentioned in both Search places and Search users API in document

### ISSUE THREAD

**Issue by arimathi14** [radarlabs/react-native-radar#108]
**"Limit: The max number of places to return" mentioned in both Search places and Search users API document**

- Search places returned places
- Search users returned users but mentioned places instead of users.

Is this expected?
![users](https://user-images.githubusercontent.com/64394789/82564556-94ad3380-9b96-11ea-80b4-f5ebe54a087b.png)
![places](https://user-images.githubusercontent.com/64394789/82564569-98d95100-9b96-11ea-883c-27b761c809e6.png)

**Comment by nickpatrick** [comment]
Great catch. Fixed. Thank you!

**Comment by arimathi14** [comment]
Thank you!!!
