### ISSUE TITLE
Device Specific Methods returning [Error: ERROR_LOCATION]

### ISSUE THREAD

**Issue by ifielder** [radarlabs/react-native-radar#109]
## Summary
Using any of the device-specific radar methods return errors from the promise
ex. 

```
getLocation()
trackOnce()
searchGeofences()
```

![Console](https://user-images.githubusercontent.com/45435978/83174689-f9f1af00-a0d7-11ea-8759-97351c3895df.png)
)

Above is the standard console output from the  example file App.js
## Code to reproduce

```
 cd /example && npm install && npm install react-native-radar@latest
```
npx react-native run android 
## Steps to reproduce
 clone react-native-radar 
add publishing key to MainActivity.java

## OS version 
Mac OS catalina 10.15.4
## SDK installation method
installed the react-native-radar example
## SDK version
3.0.0
## Other information

My initial thoughts are that in may have something to do with the google play services API

**Comment by nickpatrick** [comment]
Hey, are you testing in the emulator? Make sure high accuracy location is turned on in the device settings and make sure a location is provided in the emulator settings.

**Comment by ifielder** [comment]
Turning on high accuracy location worked for me! (using a physical device).

Thanks for the quick response!
