### ISSUE TITLE
#import <RadarSDK/RadarSDK.h>

### ISSUE THREAD

**Issue by smartdevdom** [radarlabs/react-native-radar#11]
I have problem in iOS and the framework gives me an error #import <RadarSDK / RadarSDK.h>

**Comment by smartdevdom** [comment]
Errror on Library/RNRadar.xcodeproject ....

**Comment by nickpatrick** [comment]
How are you installing the SDK?

**Comment by nickpatrick** [comment]
If you're installing with CocoaPods, the framework should automatically be added to your header search paths. If you're installing manually or with Carthage, make sure you drag `RadarSDK.framework` into the Linked Frameworks and Libraries section of your target. https://www.onradar.com/documentation/sdk#ios-add
