### ISSUE TITLE
ios app build crashes

### ISSUE THREAD

**Issue by ravi-poonia** [radarlabs/react-native-radar#115]
## Summary
The app build breaks with this error
`  [Radar searchGeofencesNear:near radius:radius tags:tags limit:limit completionHandler:completionHandler];
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Ravi/code/pckitup/agent-app/node_modules/react-native-radar/ios/RNRadar.m:400:16: error: no known class method for selector 'searchGeofencesWithRadius:tags:limit:completionHandler:'
        [Radar searchGeofencesWithRadius:radius tags:tags limit:limit completionHandler:completionHandler];
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Ravi/code/pckitup/agent-app/node_modules/react-native-radar/ios/RNRadar.m:632:29: error: use of undeclared identifier 'RadarRouteModeTransit'
            modes = modes | RadarRouteModeTransit;
                            ^
`

## SDK installation method
I have used pods and followed all the steps mentioned in the doc

## SDK version
"react-native-radar": "^3.0.2",
 pod 'RadarSDK', '~> 3.0.0'

**Comment by nickpatrick** [comment]
Hey @ravi-poonia, this should be fixed if you pin `RadarSDK` to `3.0.1`. It will also be fixed once we release #114 in the next 24 hours. I will keep you posted.

**Comment by ravi-poonia** [comment]
Should it be  `"react-native-radar": "^3.0.1",` or `pod 'RadarSDK', '~> 3.0.1'` or both?

**Comment by nickpatrick** [comment]
"react-native-radar": "^3.0.2" and `pod 'RadarSDK', '3.0.1'` (no `~>`, which would allow upgrade to `3.0.2`) should work. Let me know!

**Comment by nickpatrick** [comment]
Hey @ravi-poonia, this should be fixed in `react-native-radar` `3.0.3`, which upgrades to iOS SDK `3.0.2`. Give it a try and let us know!
