### ISSUE TITLE
Feature request- initializeWithPublishableKey in javascript

### ISSUE THREAD

**Issue by ste00martin** [radarlabs/react-native-radar#12]
Any chance of being able to set or change the initializeWithPublishableKey in ReactNative?

**Comment by coolbrow** [comment]
This is definitely something we're working on. But at the moment we need to initialize the SDK before any JS bundle is loaded to register for location callbacks, so calling initialize from ReactNative JS is potentially problematic

**Comment by coolbrow** [comment]
That's exactly the type of solution we're looking for. Splitting out the required native initialization from setting the public key.
