### ISSUE TITLE
Help with starttrip function

### ISSUE THREAD

**Issue by janogarciardz** [radarlabs/react-native-radar#143]
When executing the starttrip function, it returns an error
"Could not invoke RNRadar.startTrip"

Thank you

## OS version
Android

## SDK version
3.0.6

**Comment by nickpatrick** [comment]
Hi @janogarciardz, does this still repro for you on the latest version, `3.1.4`? https://github.com/radarlabs/react-native-radar/releases/tag/3.1.4

**Comment by janogarciardz** [comment]
The error no longer returns, but the dashboard does not reflect any change, mm it does not return it to me in the webhook events. :(

**Comment by janogarciardz** [comment]
Good afternoon, the code already works, it was my mistake.
Another question, can I have more one starTrip for user? for example I have a delivery app and a delivery person can have more than one destination.
Thank you
