### ISSUE TITLE
Create new trip from API??

### ISSUE THREAD

**Issue by janogarciardz** [radarlabs/react-native-radar#154]
Create new trip from API??

**Comment by rstims** [comment]
> Create new trip from API??

@janogarciardz I was informed the following call will "upsert" a trip.

```
curl --location --request PATCH 'https://api-staging.radar.io/v1/trips/12345' \
--header "Authorization: apikey" \
--header 'Content-Type: application/json' \
--data-raw '{
    "mode": "car",
    "status": "pending",
    "destinationGeofenceTag": "tag",
    "destinationGeofenceExternalId": "12345"
}'
```

**Comment by brettguenther** [comment]
thanks @rstims - we have an updated POST endpoint to create a trip (also used in new SDK versions). Documentation here: https://radar.com/documentation/api#create-a-new-trip
