### ISSUE TITLE
IOS significant location change not working as expected

### ISSUE THREAD

**Issue by silvester-sanjay** [radarlabs/react-native-radar#167]
Summary :   Significant location change flag does't work as expected in latest IOS version  there seems to larger location gaps when compared to other IOS version's . Also we have noticed location gaps even when application is open on foreground

OS version : 
IOS 15.2 
IOS 15.2.1

SDK version: 
3.1.10

**Comment by brettguenther** [comment]
@silvester-sanjay - if still having issues, please upgrade the Radar React Native SDK version and re-file if still experiencing issues. Also, if refiling an issue please:

1.  confirm you have enabled the location background mode (https://radar.com/documentation/sdk/react-native#ios)
2. have granted background location permissions 
3. provide tracking options in use
