### ISSUE TITLE
Checking for "Always Allow" location permission in iOS

### ISSUE THREAD

**Issue by narin** [radarlabs/react-native-radar#18]
I recently integrated Radar into my app and it's been working great.  My app only needs background tracking, so it is important that I be able to check if the user chose "Always Allow" in their iOS permissions.  

From what I can tell, the `getPermissionsStatus()` method will return `'GRANTED'` regardless of whether the user chose Always Allow, or Allow Only When Using.

Is it possible to make this more detailed so that we can determine what level of permissions the user has granted?

**Comment by RodrigoCS** [comment]
#39

**Comment by nickpatrick** [comment]
Hi, https://github.com/radarlabs/react-native-radar/releases/tag/3.0.0 adds `GRANTED_FOREGROUND` and `GRANTED_BACKGROUND` permission statuses.
