### ISSUE TITLE
warning: Ignoring InnerClasses attribute for an anonymous inner class (com.onradar.sdk.t) that doesn't come with an

### ISSUE THREAD

**Issue by smartdevdom** [radarlabs/react-native-radar#2]
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.onradar.sdk.t) that doesn't come with an

react native 0.46

**Comment by nickpatrick** [comment]
Hey @smartdevdom, sorry about this. We'll be rewriting this module in the coming weeks.

**Comment by nickpatrick** [comment]
@smartdevdom, this may be related to ProGuard changes in a recent Android SDK release. When are you seeing this warning?

**Comment by nickpatrick** [comment]
This should be resolved in Android SDK version 1.2.2.
