### ISSUE TITLE
NativeModules.RNRadar is undefined

### ISSUE THREAD

**Issue by AmeerHamzaRiaz** [radarlabs/react-native-radar#26]
Even though, I have ran the command 

>  react-native link react-native-radar

Still getting this error on run-time . Need quick fix.

Ran again to double check
```
D:\react-native-project\radar>react-native link react-native-radar
Scanning folders for symlinks in D:\react-native-project\radar\node_modules (46ms)
rnpm-install info Platform 'ios' module react-native-radar is already linked
rnpm-install info Platform 'android' module react-native-radar is already linked
```

**Comment by ntomallen** [comment]
Did you do the "Configure project" and "Add SDK to project" steps in the [SDK documentation](https://radar.io/documentation/sdk).
