### ISSUE TITLE
IOS Background tracking not working when we close app.

### ISSUE THREAD

**Issue by hasnat-fabtechsol** [radarlabs/react-native-radar#311]
## Summary
IOS Background tracking not working when we close app. It works when app is in foreground and if app is minimized but when we close it it does not work. on android it works perfectly fine. and your toolkit radar app does not work in background for ios to.
## Steps to reproduce
make a geofence and track user in foreground it will give response but when you're in background it won't try to check your own toolkit app.
## OS version

17.4.1

## SDK installation method
installed using yarn
## SDK version

sdk ios 3.9.14
  "react-native-radar": "3.10.8",
--

**Comment by lmeier** [comment]
Hi @hasnat-fabtechsol, sorry to hear that you're having issues. Looking forward to getting to the bottom of this for you.

Did you add the relevant & required fields to your `info.plist`? Instructions for that are [here](https://radar.com/documentation/sdk/ios#request-permissions).

What tracking preset are you using? How are you starting tracking? Feel free to share any code snippets relevant.

Looking at your project, I don't see any Android devices. My first instinct is that there's an implementation issue that is affecting both platforms. Looking forward to helping out here.

**Comment by hasnat-fabtechsol** [comment]
Ok main issue was I was testing by connecting device with usb so what I came to know background service works when we install bundle or use testflight that was my issue when I test with testflight it worked.
and make sure to enable background modes in info plist.

**Comment by Hosam-hsm** [comment]
Hi @lmeier, 

I have setup a basic expo app and configured radar as per the docs. I am tracking location in background in a real iOS device and sending a local notification. This is working fine while the app is in foreground or is minimised. But I am not getting the notification when the app is killed. 

```
async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You have entered a geofence! 📬",
      body: "Here is the notification body",
      data: { data: "goes here", test: { test1: "more data" } },
    },
    trigger: { seconds: 2 },
  });
}

Radar.on("location", (result: RadarLocationUpdate) => {
  schedulePushNotification();
});
```

I have tested using an eas build and testflight build. Still not receiving the local notification when app is killed. Any help here?
