### ISSUE TITLE
locationPermissionStatus not defined in RNRadar.m & throws error

### ISSUE THREAD

**Issue by mattshapiro** [radarlabs/react-native-radar#340]
## Summary
After updating to Expo 50 & React Native 0.73 (from 0.72) we began receiving a runtime error from the Radar library when interacting with the native location permissions dialog. Error states "'locationPermissionStatus' is not a supported event type for RNRadar..." (see screenshot). When I add "locationPermissionStatus" to supportedEvents() in RNRadar.m inside the react-native-radar dependency, the error goes away.

## Code to reproduce
After first launch, I believe on the call to Radar.initialize({key}), a native location permission dialog is shown. 

## Steps to reproduce
Wait for location permissions screen on first launch & select an option. Notice the error.

## OS version
iOS 17.2 (iPhone 15)

## SDK installation method
yarn add

## SDK version
Originally 3.7.4 - tried with 3.12.3

## Other information
Screenshot:
<img width="374" alt="Screenshot 2024-07-10 at 11 24 49 AM" src="https://github.com/radarlabs/react-native-radar/assets/966612/f9aead5c-9145-43d5-8ce8-a2a9d0a64b7c">

**Comment by KennyHuRadar** [comment]
Hey @mattshapiro , this issue should be resolved in our most recent 3.13.0 release :)

**Comment by KennyHuRadar** [comment]
Closing as completed
