### ISSUE TITLE
Compile errors from Android SDK when building with 3.18.3

### ISSUE THREAD

**Issue by mattshapiro** [radarlabs/react-native-radar#360]
## Code to reproduce
NA (no code changes)

## Steps to reproduce
When we got the latest version (3.18.3) and build our project for Android, it fails with the following errors:
`/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1119: error: '(' or '[' expected
        Radar.validateAddress(address, new RadarValidateAddressCallback {
                                                                        ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: <identifier> expected
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                      ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: <identifier> expected
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                         ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: illegal start of type
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                          ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: ';' expected
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                                   ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: <identifier> expected
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                                                         ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: illegal start of type
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                                                          ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: ';' expected
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                                                                   ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1121: error: ';' expected
            onComplete(@NonNull Radar.RadarStatus status, @Nullable RadarAddress address, @Nullable RadarAddressVerificationStatus verificationStatus) {
                                                                                                                                                     ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1122: error: illegal start of expression
                if (status == Radar.RadarStatus.SUCCESS && ) {
                                                           ^
/Users/.../app/.../node_modules/react-native-radar/android/src/main/java/io/radar/react/RNRadarModule.java:1135: error: illegal start of expression
        });
         ^
11 errors
`

Changing the dependency version to anything other than 3.18.3 resolves the issue.

## OS version
MacOS Sonoma 14.6.1

## SDK installation method
yarn/npm

## SDK version
3.18.3

## Other information
We are using React Native but this does seem to be coming from within the actual Radar Android SDK from what we can tell.

**Comment by lmeier** [comment]
Hey @mattshapiro — thanks for flagging. We're looking into this and will update tomorrow.

**Comment by lmeier** [comment]
@mattshapiro this has been fixed in the latest release: https://github.com/radarlabs/react-native-radar/releases/tag/3.18.4

Thanks for identifying! Will close this out but please chime back in if you run into anything else. 😄 🙏

**Comment by mattshapiro** [comment]
Thanks for the quick turnaround!
