### ISSUE TITLE
iOS Linking Problem

### ISSUE THREAD

**Issue by reevesnick** [radarlabs/react-native-radar#42]
I followed the directions to link the module from the iOS version of the React Native Application. After linking the Android Portion works fine but the iOS version return this message dealing with the RNRadar Framework. I also added the iOS Framework for the iOS project and still return the same error message

`'RadarSDK/RadarSDK.h' file not found`

**Comment by coolbrow** [comment]
Hey there, how are you adding and linking the iOS Radar Framework, with CocoaPods, Carthage or manually? 

If you're using Carthage or manual, you'll have to make sure the framework is linked in the `Link Binary With Libraries` Build Phase in your project settings.

**Comment by reevesnick** [comment]
It linked manually. This is an existing project and I don't want to recreate using CocoaPods. I added the iOS SDK and producing the same result.

**Comment by reevesnick** [comment]
This is some screenshots going on Xcode Version 10.0

![screen shot 2018-11-14 at 11 09 40 am](https://user-images.githubusercontent.com/7657968/48506244-d882e800-e7fd-11e8-9c8a-013ec47bb198.png)
![screen shot 2018-11-14 at 11 09 29 am](https://user-images.githubusercontent.com/7657968/48506253-dd479c00-e7fd-11e8-9e57-46f6a07f39d0.png)

**Comment by coolbrow** [comment]
Mind sharing your build details?
- Version of radar-react-native
- Version of Radar iOS SDK
- Screenshot or details of your `Link Binary With Libraries` Build Phase

**Comment by reevesnick** [comment]
Version of radar-react-native: 2.0.4. 2.1.0 was giving problems for the Android project so I reverted back
iOS Version was 2.0.4 but recently upgraded to 2.1.0.
Screenshot: 
![screen shot 2018-11-14 at 11 27 58 am](https://user-images.githubusercontent.com/7657968/48507316-724b9480-e800-11e8-8dbc-7ffed06af3ac.png)

Location Path : Project_Root/ios/RadarSDK.framework

**Comment by coolbrow** [comment]
Thanks, will look into it. Mind opening another issue for the 2.1.0 android bug?

**Comment by reevesnick** [comment]
Yes. Will open soon

**Comment by coolbrow** [comment]
Would you also mind sharing your `Framework Search Paths` (from Build Settings) in both your top-level app target *and* the embedded `RNRadar.xcodeproj`, see image below:

<img width="236" alt="screen shot 2018-11-14 at 4 03 06 pm" src="https://user-images.githubusercontent.com/1281199/48512186-de40f380-e826-11e8-81a9-0ac83dcee8e8.png">

**Comment by reevesnick** [comment]
Yes. Of course
![screen shot 2018-11-14 at 1 14 30 pm](https://user-images.githubusercontent.com/7657968/48512829-4552ae00-e80f-11e8-84fe-02cff39bb35f.png)
![screen shot 2018-11-14 at 1 14 01 pm](https://user-images.githubusercontent.com/7657968/48512838-48e63500-e80f-11e8-9cc2-d0d32e728f4b.png)

**Comment by reevesnick** [comment]
Just in the embedded project. When I imported into the App Delegate with the included imports, it works fine.

**Comment by coolbrow** [comment]
Here's what my search paths look like in a working test project: 
<img width="518" alt="screen shot 2018-11-15 at 10 48 09 am" src="https://user-images.githubusercontent.com/1281199/48564253-03d00a80-e8c4-11e8-9740-be19cdf0735c.png">

I've removed the pods and have basically the same setup as you described, so you can ignore the pod-specific search path. Does adding `$(inherited)` to the list fix your issue?

**Comment by reevesnick** [comment]
It works now. I just have to put the folder path without mentioning RadarSDK.framework. Sorry about that

**Comment by coolbrow** [comment]
Not a problem! Thanks for the report, we'll look into having better default search paths to prevent these kinds of issues in future versions.
