### ISSUE TITLE
Permissions on android

### ISSUE THREAD

**Issue by rogueturnip** [radarlabs/react-native-radar#49]
Hi,

I've got radar up and working in both iOS and Android but I'm wondering about about asking for permissions on android.  When I updated my app on iOS it asked for permissions but with the same code it didn't ask for permission in Android.  When I turned on location manually for the app it worked just fine.

Is there anything in particular I need to do to get the permissions in android? I followed the sdk.

Tony

**Comment by coolbrow** [comment]
I'm not familiar with the `RootStack` class, is this a visible screen in your application?

**Comment by rogueturnip** [comment]
I'm using react-navigation to do tabs with stacks under that.  The root decides which path to take, whether to go to the signin or to go to the authenticated tabs.  I'm guessing that I need to move the permissions to a different point that actually renders something.

**Comment by coolbrow** [comment]
Yes, you'll need to request permission during the visible lifecycle of your app, at least for the Android implementation.

**Comment by rogueturnip** [comment]
I hate to be a pest on this.  I tried moving it into my main tab that is rendered and it's still not doing a prompt for permissions.  Tried with a fresh app install too.

**Comment by coolbrow** [comment]
What device and OS are you testing on? Are you seeing any errors? Are you able to get a location at all?

**Comment by rogueturnip** [comment]
I’ve tried with a Pixel 2 XL and a Samung S9+ both don’t get the permissions box.  If I manually go into app settings and turn on Location both send the location.

It’s just the permission box that isn’t working.

I’ve tested in iOS and it works just fine.

My app uses react-navigation bottomTabs as part of the layout.

I’m not seeing any errors it’s just not showing the permission box.

Sent from Mail for Windows 10

**Comment by rogueturnip** [comment]
I’ve bumped the SDK up to 28.0.3 (using gradle 4.6 so that’s defaulted now).

My code is in componentDidMount as such:

            Radar.setUserId(this.state.userId);
            Radar.getPermissionsStatus().then((status) => {
                console.log('RADAR:',status);
                if (status === "UNKNOWN") {
                    console.log('RADAR ask permissions');
                    Radar.requestPermissions(true);
                }
            });
            Radar.trackOnce().then((result) => {
                // do something with result.events, result.user.geofences
                console.log("RADAR EVENT:",result);
              }).catch((err) => {A
                console.log("RADAR ERror:",err);
                // optionally, do something with err
              });
            Radar.startTracking();



Sent from Mail for Windows 10

**Comment by coolbrow** [comment]
Sorry, which _Radar_ sdk version are you using?

**Comment by rogueturnip** [comment]
Latest from npm 2.1.2.  This is new functionality in our app so started with latest.

Sent from Mail for Windows 10

**Comment by coolbrow** [comment]
Oh I see the issue! Android will never return `UNKNOWN` status, that's an iOS result only. It is either `GRANTED` or `DENIED` on Android. You should probably request in the denied case as well or have a special case for Android. 

Sorry for the confusion, we'll update our docs accordingly.

**Comment by rogueturnip** [comment]
Thanks for the help!
