### ISSUE TITLE
Gravity forms extension not locking download files

### ISSUE THREAD

**Issue by gabygaby2018** [radarlabs/react-native-radar#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Metadata (please complete the following information):**
 - React Native Radar Version: [e.g. 2.1.2]
 - Platform: [e.g. iOS, Android, both]
 - Device [e.g. Pixel 2 XL, iPhone X]
 - Device OS Version [e.g. Android 9.0 (Pie), iOS 12]

**Additional context**

**Comment by gabygaby2018** [comment]
Hi all, I am having troubles trying to make Gravity forms extension for Download Monitor works. Apparently everything is well set, but users can download files without filling the forms! What might be happenning?

**Comment by coolbrow** [comment]
I think you might have the wrong repository, this is the repository for https://www.npmjs.com/package/react-native-radar
