### ISSUE TITLE
The callback trackOnce() exists in module RNRadar, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by atkit** [radarlabs/react-native-radar#61]
**Describe the bug**
trackOnceWithCompletionHandler is calling its callback more than once and it is not allowed to resolve Promise twise or more 

**To Reproduce**
1. tracking has been started already 
2. call trackOnce it will result with Promised callback 
3. a few seconds later it will try to resolve again

**Expected behavior**
it needs to be called once 

**Screenshots**
![image-1](https://dl.dropbox.com/s/uoa26j7d0sjb01j/screen-1.png)
![image-2](https://dl.dropbox.com/s/dg51nivp7v2d8w5/screen-2.png)

**Metadata (please complete the following information):**
 - React Native Radar Version: [e.g. 2.1.2]
 - Platform: [both]
 - Device [iPhone X]
 - Device OS Version [12]

**Comment by coolbrow** [comment]
Thanks for the report. To clarify, you're seeing this error on Android as well? Mind sharing a code snippet of the JavaScript calling method?

**Comment by atkit** [comment]
```
    Radar.on("events", (data) => trackRadarEvent("events", data));
    Radar.on("location", (data) => trackRadarEvent("location", data));
    Radar.on("error", (data) => trackRadarEvent("error", data));
    Radar.trackOnce()
      .then((result) => {
        console.log(result);
      })
      .catch((err) => {
        console.log(err);
      });
```

startTracking was called before in previous session

**Comment by coolbrow** [comment]
Thanks, does this happen 100% consistently? On Android as well?

**Comment by coolbrow** [comment]
@atkit We are able to reproduce locally and have a fix on the way. In short, the added main queue requirement
```
- (dispatch_queue_t)methodQueue {
    return dispatch_get_main_queue();
}
```
is causing our callback to be called twice. We will add a guard against this in our next release, which should be very soon. Thanks for the report and patience.
