### ISSUE TITLE
RNRadarTests.m cannot be found

### ISSUE THREAD

**Issue by vadimshvetsov** [radarlabs/react-native-radar#65]
Hello everyone. I would appreciate any suggestion, what I do wrong or it's a bug with the latest release?

**Describe the bug**
RNRadarTests.m cannot be found while building the app

**To Reproduce**
- `npm i react-native-radar`
- `react-native link react-native-radar`
- add `NSLocationAlwaysAndWhenInUseUsageDescription` and `NSLocationAlwaysUsageDescription` keys to `Info.plist` and `fetch` with `location` strings to `UIBackgroundModes` key.

- add Radar SDK. Here is my `Podfile`
```ruby
platform :ios, '9.0'
inhibit_all_warnings!

target 'QleanCleaners' do
  # Pods for QleanCleaners
  pod 'RadarSDK', '~> 2.1.0'

  target 'QleanCleanersTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
```

- `pod install`
- build the app with react-native or xcode

**Expected behavior**
App builds successfully via react-native run as well as via XCode

**Screenshots**

**Metadata (please complete the following information):**
 - React Native Radar Version: 2.1.4
 - Platform: iOS
 - Device: iPhone 5s
 - Device OS Version: iOS 12

**Additional context**
```
Showing All Messages
:-1: Build input file cannot be found: '/Users/User/project/Qlean/cleaners/node_modules/react-native-radar/ios/RNRadarTests/RNRadarTests.m'

error: Build input file cannot be found: '/Users/User/project/node_modules/react-native-radar/ios/RNRadarTests/RNRadarUtilsTests.m'
```

**Comment by coolbrow** [comment]
@vadimshvetsov - this should be fixed in the latest version: https://github.com/radarlabs/react-native-radar/releases/tag/2.1.5

Please let us know if you continue to have problems after upgrading.
