### ISSUE TITLE
react native 0.58.4

### ISSUE THREAD

**Issue by rogueturnip** [radarlabs/react-native-radar#74]
I'm trying to compile my app with 0.58.4 and other than upgrading the react native version (following usual upgrade steps) I've started seeing a compile problem using react-native run-ios

I've attempted removing node_modules, clearing the pods to no success.

What I'm seeing for errors seems to land in the RadarSDK around Folly and boost-react-native.

In file included from /Users/tony/alana-mobile/node_modules/react-native-radar/ios/RNRadar.m:4:
In file included from /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:17:
/Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h:11:10: warning: non-portable path to file '<Math.h>'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include <math.h>
         ^~~~~~~~
         <Math.h>
In file included from /Users/tony/alana-mobile/node_modules/react-native-radar/ios/RNRadar.m:4:
In file included from /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:17:
In file included from /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h:11:
In file included from ../../../ios/Pods/Folly/folly/math.h:26:
In file included from ../../../ios/Pods/boost-for-react-native/boost/tr1/tr1/limits:16:
In file included from ../../../ios/Pods/boost-for-react-native/boost/tr1/detail/config_all.hpp:43:
../../../ios/Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstddef:10:1: error: unknown type name 'namespace'
namespace std {
^
../../../ios/Pods/boost-for-react-native/boost/compatibility/cpp_c_headers/cstddef:10:14: error: expected ';' after top level declarator

**Comment by coolbrow** [comment]
Thanks for the report, what version of `react-native-radar` are you using, and what was the previous version combination (react native version + `react-native-radar` version) that compiled successfully?

**Comment by rogueturnip** [comment]
I'm running 2.1.8 with SDK 2.1.3.

I took a look in your project.pbxproj file and noticed this:
                                HEADER_SEARCH_PATHS = (
                                        "$(inherited)",
                                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
                                        "$(SRCROOT)/../../../React/**",
                                        "$(SRCROOT)/../../react-native/React/**",
                                        "${SRCROOT}/../../../ios/Pods/RadarSDK/**",
                                        "${SRCROOT}/../../../ios/RadarSDK/**",
                                        "$(SRCROOT)/Carthage/Build/iOS/**",
                                        "${SRCROOT}/../../../ios/**",
                                );
From what I understand is that "${SRCROOT}/../../../ios/**" can cause issues so I removed that and the compile goes farther to this error now:

ld: warning: directory not found for option '-L/Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/React'
duplicate symbol _OBJC_CLASS_$_RNRadarUtils in:
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/react-native-radar/libreact-native-radar.a(RNRadarUtils.o)
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/libRNRadar.a(RNRadarUtils.o)
duplicate symbol _OBJC_METACLASS_$_RNRadarUtils in:
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/react-native-radar/libreact-native-radar.a(RNRadarUtils.o)
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/libRNRadar.a(RNRadarUtils.o)
duplicate symbol _OBJC_IVAR_$_RNRadar.hasListeners in:
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/react-native-radar/libreact-native-radar.a(RNRadar.o)
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/libRNRadar.a(RNRadar.o)
duplicate symbol _OBJC_IVAR_$_RNRadar.locationManager in:
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/react-native-radar/libreact-native-radar.a(RNRadar.o)
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/libRNRadar.a(RNRadar.o)
duplicate symbol _OBJC_CLASS_$_RNRadar in:
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/react-native-radar/libreact-native-radar.a(RNRadar.o)
    /Users/tony/alana-mobile/ios/build/Build/Products/Debug-iphonesimulator/libRNRadar.a(RNRadar.o)

**Comment by rogueturnip** [comment]
oh sorry, also the version that did work for me were React native 0.57.9 and Radar react native 2.1.7 SDK 2.1.0.

**Comment by coolbrow** [comment]
That's interesting, we didn't change anything from version 2.1.7 regarding search paths, I'm guessing it has to do with some change in React Native. 

Would you mind sharing some details about your upgrade process? Any other code changes since the last time it compiled?

**Comment by rogueturnip** [comment]
There are no code changes to the react-native code base other than the upgrade in Radar and React Native.

My upgrade process was 
react-native-git-upgrade
Add the Javascript Framework to XCode
Clear node_modules
Clear .rncache
Clear and reinstall Pods

Does this help?

Sent from Mail for Windows 10

**Comment by coolbrow** [comment]
Did you run `react-native link react-native-radar` command after reinstalling the node module and before running `pod install`? The link command links the iOS framework for you and also sets up the local pod for the library.

**Comment by rogueturnip** [comment]
I just tried that and got the same error (I put the original SRC lines back in the project file).

Sent from Mail for Windows 10

**Comment by rogueturnip** [comment]
I tried react-native run-android and it works fine so it seems to be something with iOS only.

**Comment by rogueturnip** [comment]
Not sure if this helps or not but I tried to build in XCode 10 and I got this
Argument list too long: recursive header expansion failed at /Users/tony/alana-mobile/node_modules/react-native-radar/ios/../../../ios/build/Index/DataStore/v5/records/79.

**Comment by rogueturnip** [comment]
I solved it.  I had to do a react-native unlink react-radar-native and then relink it.  Very strange but the build is succeeding now.
