### ISSUE TITLE
Radar.on events not firing in background mode on iOS using RN 0.59.1

### ISSUE THREAD

**Issue by levi-beers** [radarlabs/react-native-radar#76]
It's very possible I'm not doing something right, however, these are the steps I've taken:

1. Install RN 0.59.1 with react-native init
2. Configure cocoapods for use
3. Install react-native-radar
4. Configure RadarSDK in pods, then run pods install
5. Change AppDelegate.m & include radar key
6. Add CoreLocation to Frameworks & Libraries in XCode
7. Change "Capabilities" to account for background fetch & location updates
8. Run code

**Describe the bug**
Radar registers the user, reports the initial location and provides location updates when iOS simulator is in "Freeway Drive" location mode approximately every 2.5 to 4.5 minutes. When app is put in background mode, no location events, error or radar events are sent until the app is in foreground.

**To Reproduce**
See GitHub of this issue: [https://github.com/levi-beers/RadarTest1](https://github.com/levi-beers/RadarTest1)

**Expected behavior**
Radar.on events should fire while app is in background mode.

**Screenshots**
Reactotron.log
<img width="563" alt="Screen Shot 2019-03-22 at 12 31 31 AM" src="https://user-images.githubusercontent.com/16378407/54801128-d2819580-4c3b-11e9-884b-f3554270ec2f.png">

Background Modes
<img width="978" alt="Screen Shot 2019-03-22 at 12 46 16 AM" src="https://user-images.githubusercontent.com/16378407/54801161-edeca080-4c3b-11e9-9caf-44d931a68b07.png">

**Metadata (please complete the following information):**
 - React Native Radar Version: 2.1.2
 - Platform: iOS
 - Device iPhoneX
 - Device OS Version [iOS12]

**Comment by russellcullen** [comment]
Thanks for the very detailed report, much appreciated. 

Does this behavior happen on the latest version of `react-native-radar` (at this time, `2.1.8`)? 

Also do you see any updates in the radar dashboard for that user while the app is backgrounded?

Thanks for the sample project, we'll look into that asap.

**Comment by levi-beers** [comment]
I put the wrong metadata in the ticket, I'm actually using 2.1.8 -- I had to check the packages.json in the github example to make sure. Going to test a few RN versions back to see if the same behavior persists and it's more likely something I've done. I'm using XCode 10.1 for the iOS build if that makes any difference.

**Comment by russellcullen** [comment]
Ok cool, thanks. Your sample code and setup steps look sound. The team is going to load up and run your sample code as soon as we can to see if we have similar behavior, we'll let you know if we have any findings from that.

Does it appear that the user is still being updated in the Radar dashboard? If it's just client events that aren't being delivered it could be indicative of a react native issue. If you are not seeing any updates in the dashboard either, the issue is more likely to be a background tracking/permissions problem.

**Comment by levi-beers** [comment]
Just did a test with the dashboard. It doesn't appear to be sending any updates to the dashboard while in background mode. It's been 10 minutes with the app still running and no updates, but as soon as I brought it to the foreground it sent an event to dashboard.

**Comment by russellcullen** [comment]
Alright thanks for the info, that behavior could mean that the app is not receiving location in the background for some reason. Are you requesting (and accepting) 'Always' location permissions?

I took a quick look at the sample again and I see:
`Radar.requestPermissions("background")` however that API takes a boolean, not a string, this could be the issue.

**Comment by levi-beers** [comment]
Sheesh. I don't even know how I missed that. Thank you @russellcullen -- you've been extremely helpful and responsive. Hopefully I don't screw up the Android implementation as bad, ha!

**Comment by russellcullen** [comment]
No worries, glad I could help! Please let us know if you run into any more issues, always happy to help. 😄
