### ISSUE TITLE
Functions passed to Radar.on('location') not firing in background but get updates on dashboard

### ISSUE THREAD

**Issue by dereknelson** [radarlabs/react-native-radar#77]
**Describe the bug**
The function I pass to `Radar.on('location')` only runs in the foreground - when it's foregrounded, I get requests to my remote API, however, in the background, I will not, despite still receiving events on the dashboard. The functions are in the global scope of my project. 

**To Reproduce**
Not sure how to reproduce, but here's my setup (with some stuff omitted for clarity)
```
export async function initializeRadar(){
    Radar.trackOnce().then((result) => {
        console.log('trackonce', result)
    }).catch((err) => {
        console.log('trackerror', err)
    });
    Radar.startTracking({
        priority: 'responsiveness', // // use 'efficiency' to avoid Android vitals bad behavior thresholds (ignored on iOS)
        sync: 'possibleStateChanges', // use 'all' to sync all location updates ('possibleStateChanges' recommended)
        offline: 'replayStopped' // use 'replayOff' to disable offline replay ('replayStopped' recommended)
    })
}

Radar.on('location', async result => {
    console.log('location result', result)
    const res = await Promise.all([AsyncStorage.getItem('userToken'), AsyncStorage.getItem('username')]), token = res[0], username = res[1]
    try {
        if (username == 'derek') Notifications.presentLocalNotificationAsync({ title: 'hey', body: `new location update`, })
        let geofences = await api.sendLocation({ coords: result.location, token })
        console.log('geofences', geofences)
    } catch (error) {
        console.log('axios error', error)
        Sentry.logMessage(new Error(error))
    }
})
```
**Expected behavior**
The function to generate a push notification as well as make a network request to my API like it does in the foreground.

**Screenshots**
Latest event on the [dashboard](http://prntscr.com/ncy6u3), latest received event [on my api](http://prntscr.com/ncy6i4) (last time the app was open)

**Metadata:**
 - React Native Radar Version: 2.1.8
 - Platform: iOS
 - Device: iPhone X
 - Device OS Version: iOS 12.1

**Additional context**
My app is an ejected [Expo](expo.io) app.

**Comment by vadimshvetsov** [comment]
I have the same problem here
https://github.com/radarlabs/react-native-radar/issues/75

**Comment by russellcullen** [comment]
@vadimshvetsov This looks to be separate from #75 as this is an iOS issue - is that correct @dereknelson? Otherwise will close this as a duplicate. 

@dereknelson Are you seeing the any logs from the callback in the background? Specifically the `location result` and `geofences` logs? Making asynchronous calls in the background is inherently flakey (see #75 for details in an Android context) so it's best to verify behavior locally as many factors could cause the network request to fail. 

I'd suggesting using a [webhook](https://radar.io/documentation/integrations#event-integrations-webhooks) to send Radar events directly to your back-end.

**Comment by dereknelson** [comment]
@russellcullen it is an iOS issue. I haven't had a chance to dive into the logs, I read through #75 but I'm pretty sure it's not being called at all for two reasons:
1. I have sentry logging errors to see if the network request fails for any reason (which I forgot to add in my snippet earlier)
2. despite `Notifications.presentLocalNotificationAsync` seeming like an async call it does happen immediately, I've yet to get it to trigger in the background. I've used other background tracking libraries and I've gotten that notification to be triggered in the background.

**Comment by russellcullen** [comment]
Thanks for the info, this is definitely not intended behavior. Although it's possible the `AsyncStorage.getItem` calls are not able to complete before the app is suspended, I wouldn't expect this to be the case.  

Just to help debug would you mind implementing a super simple callback, something like:
```
Radar.on('location', result => {
    console.log('location result', result)
})
```

I don't expect that the `async` callback would change background behavior but we hand that off to the React Native event emitter and there could be an issue with that. 

Additionally, do previous versions behave the same for you?

**Comment by dereknelson** [comment]
@russellcullen a few things: I usually try to do my due diligence in testing before opening an issue (but there's no way you could've known that) so I'm pretty confident the function is not getting called at all.

1. the reason I have the AsyncStorage call is because this code is in production and I don't want to spam other users with notifications. I have tried the simple call back, the first time I implemented it it was just me using testflight with the build so I didn't need the `if (username is me)`. The code was exactly the following, which resulted in no logs/notifications:
```
Radar.on('location', result => {
    console.log('location result', result)
    Notifications.presentLocalNotificationAsync({ title: 'hey', body: `new location update`, })
})
```
I originally had it in that `async function initializeRadar` but moved it to the global scope to see if that was the issue.

2. I have not tried previous versions. Which versions do you advise I try? Building a new bundle and submitting to testflight is a bit of a process so I want to be sure I don't waste an hour each time only to discover I didn't go back far enough or whatever.

3. We authenticate users using a JWT, how would I go about giving that to the SDK so that the webhook would be able to post to my API with each user's respective token? 
Thanks for your help :)

**Comment by russellcullen** [comment]
Thanks for the information, I appreciate all the due diligence you've already done. 

2 - Don't worry about testing previous versions if a full release cycle is needed, definitely more work than it's worth, no worries

3 - You can set generic key/value data on each user with `Radar.setMetadata()`. This metadata will be available in webhooks, api, and the dashboard in `user.metadata`. For this setup you'll need to have a singular webhook endpoint that verifies the token set in `user.metadata`. 

In any case, it's odd you're not seeing callbacks in the background. If you wouldn't mind sharing where and when the event callback is registered. The function is in global scope, which is great, but when in the app lifecycle is the event being registered? Similarly, do you mind sharing your app delegate? The Radar React Native SDK needs the js bundle to be loaded when the app is loaded in the background to deliver events, it's possible this isn't happening for some reason.

**Comment by dereknelson** [comment]
I call `initializeRadar` in the componentDidMount of my navigator class, which is the direct child of App.js. 

Here's my [AppDelegate](https://gist.github.com/dereknelson/1ee14b472f33cf339cac53828c69d589). Full disclosure, I've been using Expo's managed workflow (JS only) to develop my app until about a month ago when I ejected, so my only experience with the native side of things has been in the last month so I'm kinda in over my head.

**Comment by russellcullen** [comment]
No worries, happy to help! 

All that comment means is the `EXStandaloneAppDelegate` which your AppDelegate inherits from (I assume, this is defined in your `AppDelegate.h`) is doing all heavy lifting in _it's_ `application:didFinishLaunchingWithOptions` method, which you call on line 16 of that gist. 

You can see implementation of that superclass [here](https://github.com/expo/expo/blob/master/ios/Exponent/ExpoKit/EXStandaloneAppDelegate.m)

From [line 42](https://github.com/expo/expo/blob/master/ios/Exponent/ExpoKit/EXStandaloneAppDelegate.m#L42) of the source, it appears the JS bundle isn't loaded unless the app is loading into the foreground. Although I'm not an expert in Expo or ExpoKit so I can't be sure.

After reading through the ExpoKit source a little more, it seems as though none of the javascript at all is loaded unless the app is in the foreground, does this align with the behavior you're seeing (0 callbacks, from any source, in the background)?  

Unfortunately from what I can tell, our SDK simply isn't compatible with ExpoKit out of the box at the moment. You'll have to eject completely/write your own app delegate to load the js bundle, for example, this is what we do in our test app:

```
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                   moduleName:@"your-module-name"
                                                   initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
```

We'll add ExpoKit support to our roadmap as making the Radar SDK easy to use is one of our top priorities, and we'll also make sure we call out this limitation in the docs. Apologies for the inconvenience here.

**Comment by dereknelson** [comment]
It would align with the behavior I'm seeing - in development, my expo-cli instance will tell me when it connects to the simulator. For now, using the webhook should be sufficient. 

Thanks for the help getting to the bottom of this, gives me a lot of insight as to why other BGLoc libraries were quirky as well.

**Comment by Levi-ackerman** [comment]
@russellcullen Any update for this problem. I still don't receive any information on `onLocation` callback when app is in background. When app is in foreground, It work.

**Comment by russellcullen** [comment]
Are you seeing the issue on iOS or Android? Are you using ExpoKit like mentioned above?

**Comment by Levi-ackerman** [comment]
@russellcullen Thank for your response.
Currently, I have tested in iOS. I don't use CRNA. 
I just want to send a local notification when user go to specific location. When app is in foreground, it work well but when app go to background, I don't see any callback invoke.

**Comment by russellcullen** [comment]
Are you using ExpoKit or Expo? If not, this issue thread is unrelated and I'd suggested opening a new bug report with all the details of your implementation, thanks.

**Comment by dereknelson** [comment]
@russellcullen just for reference, [CRNA](https://github.com/react-community/create-react-native-app) aka create-react-native-app is an (old) alias for expo.

**Comment by russellcullen** [comment]
Yeah, being an expo (or CRNA) app doesn't really matter since we force you to eject anyways. What's important is how ExpoKit handles background in this particular issue. Edited previous comment for clarity, thanks.
