### ISSUE TITLE
setPlacesProvider doesn't work

### ISSUE THREAD

**Issue by ste00martin** [radarlabs/react-native-radar#78]
**Describe the bug**
When I try to set the places provider in Android it fails to compile.

**To Reproduce**
put in radar:
```java
import io.radar.sdk.Radar;
...
  @Override
  public void onCreate() {
Radar.initialize(LIVE_RADAR_KEY);
Radar.setPlacesProvider("facebook");
  }
```
see the error output:
```
> Task :app:compileDebugJavaWithJavac FAILED
/Users/stefan-work/repos/volta/mobile/android/app/src/main/java/com/volta/android/MainApplication.java:125: error: incompatible types: String cannot be converted to RadarPlacesProvider
    Radar.setPlacesProvider("facebook");
                            ^
```

I also tried adding in `RadarPlacesProvider` to no avail:
```java
import io.radar.sdk.Radar;
...
  @Override
  public void onCreate() {
Radar.initialize(LIVE_RADAR_KEY);
Radar.setPlacesProvider(RadarPlacesProvider.FACEBOOK);
  }
```
error output:
```
> Task :app:compileDebugJavaWithJavac FAILED
/Users/stefan-work/repos/volta/mobile/android/app/src/main/java/com/volta/android/MainApplication.java:125: error: cannot find symbol
    Radar.setPlacesProvider(RadarPlacesProvider.FACEBOOK);
                            ^
  symbol:   variable RadarPlacesProvider
  location: class MainApplication
```

**Expected behavior**
setting the places provider should compile / work

**Metadata (please complete the following information):**
 - React Native Radar Version: 2.1.8
 - Platform: Android
 - Device any
 - Device OS Version any

**Comment by russellcullen** [comment]
The enum version is correct, are you importing `RadarPlacesProvider`? Alternatively you can use `Radar.RadarPlacesProvider` since `Radar` is already imported. 

It's worth noting that you can set places provider in JavaScript if that's more convenient
```
Radar.setPlacesProvider("facebook")
```

**Comment by ste00martin** [comment]
when I tried setting it in java as your suggestion I got the following error:
```sh
android/app/src/main/java/com/volta/android/MainApplication.java:127: error: cannot find symbol
    Radar.setPlacesProvider(Radar.RadarPlacesProvider);
                                 ^
  symbol:   variable RadarPlacesProvider
  location: class Radar
1 error
```
I'll just use the javascript for now but it'd be nice to show the steps to add it in on android via importing `RadarPlacesProvider`. your documentation doesn't state where that lives or how to import that package

**Comment by russellcullen** [comment]
Apologies for the confusion, we'll be sure to update the documentation. 

And sorry I was a little unclear with my previous suggestion, you'll need to import the enum class `RadarPlacesProvider` as normal and use the `FACEBOOK` enum value as you had before. All of these are valid Java:

```java
import io.radar.sdk.Radar;
import io.radar.sdk.Radar.RadarPlacesProvider;
...
@Override
public void onCreate() {
    Radar.setPlacesProvider(RadarPlacesProvider.FACEBOOK);
}
```

or alternatively
```java
import io.radar.sdk.Radar;
...
@Override
public void onCreate() {
    Radar.setPlacesProvider(Radar.RadarPlacesProvider.FACEBOOK);
}
```

you can even specify the fully qualified package and don't need to import at all:
```java
@Override
public void onCreate() {
    Radar.setPlacesProvider(io.radar.sdk.Radar.RadarPlacesProvider.FACEBOOK);
}
```
