### ISSUE TITLE
iOS manual linking error: framework not found RadarSDK

### ISSUE THREAD

**Issue by JPabloObando** [radarlabs/react-native-radar#79]
**Describe the bug**
I followed the instructions to install the library in my project, after all the steps I receive this error when compiling:

ld: framework not found RadarSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**To Reproduce**
 1. First I ran the npm install react-native-radar and the react-native link react-native-radar.
2. Copy the RadarSDK.framework into my ios folder.
3. Add the RadarSDK.framework reference from xcode.
4. Compile.

I checked the Link Binary With Libraries section and the SDK appears there.

**Expected behavior**
I cannot import <RadarSDK/RadarSDK.h> because it says "file not found".

**Screenshots**

<img width="840" alt="Screen Shot 2019-05-03 at 11 26 41 AM" src="https://user-images.githubusercontent.com/32121778/57154602-8ecf8f00-6d96-11e9-98e7-853cbd456d1b.png">
<img width="857" alt="Screen Shot 2019-05-03 at 11 27 00 AM" src="https://user-images.githubusercontent.com/32121778/57154603-8ecf8f00-6d96-11e9-81c7-d02715b9595d.png">
<img width="870" alt="Screen Shot 2019-05-03 at 11 27 09 AM" src="https://user-images.githubusercontent.com/32121778/57154605-8ecf8f00-6d96-11e9-95ed-0076d4c14637.png">
<img width="878" alt="Screen Shot 2019-05-03 at 11 27 19 AM" src="https://user-images.githubusercontent.com/32121778/57154606-8f682580-6d96-11e9-879c-7f14ae7777a3.png">
<img width="326" alt="Screen Shot 2019-05-03 at 11 27 32 AM" src="https://user-images.githubusercontent.com/32121778/57154607-8f682580-6d96-11e9-9ed2-9723a571403d.png">
<img width="442" alt="Screen Shot 2019-05-03 at 11 27 47 AM" src="https://user-images.githubusercontent.com/32121778/57154608-8f682580-6d96-11e9-96d1-473a5ad009b6.png">

**Metadata (please complete the following information):**
 - React Native Radar Version: 2.1.8
 - Platform: iOS
 - Device: iPhone 6
 - Device OS Version iOS 11

Thanks for your help!

**Comment by JPabloObando** [comment]
Fixed

**Comment by russellcullen** [comment]
Hey @JPabloObando - out of curiosity, what was the problem you ran into? Is there anything we can add to the docs to make integration easier?
