### ISSUE TITLE
 Could not find any version that matches com.android.support:support-v4:[26.0.0,).

### ISSUE THREAD

**Issue by smartdevdom** [radarlabs/react-native-radar#8]
Could not find any version that matches com.android.support:support-v4:[26.0.0,).

**Comment by nickpatrick** [comment]
This happened because we raised the v4 support library version dependency to `26.0.0` or higher in Android SDK `1.2.14`. We lowered it back to `23.0.0` in Android SDK `1.2.15` (https://github.com/radarlabs/radar-sdk-android/releases/tag/1.2.15).
