### ISSUE TITLE
IOS Build failure in relation with OCMock

### ISSUE THREAD

**Issue by andersonqi** [radarlabs/react-native-radar#80]
**Describe the bug**
I get the following error in IOS. 'OCMock/OCMock.h' file not found 
Following the documentation.

**To Reproduce**
1. npm install react-native-radar
2. react-native link react-native-radar
3. Add key to plist 
4. Add pod 'RadarSDK', '~> 2.1.0'
5. Add CoreLocation

**Expected behavior**

**Screenshots**

**Metadata (please complete the following information):**
 - React Native Radar Version: [2.1.8]
 - Platform: [iOS]

**Additional context**

**Comment by jimjeffers** [comment]
I'm having this issue as well.

**Comment by jimjeffers** [comment]
I solved this by removing the test target and linked frameworks inside of the workspace. First remove the test target by selecting it and hitting the minus button:

<img width="1006" alt="Screen Shot 2019-06-19 at 9 55 22 AM" src="https://user-images.githubusercontent.com/9150/59785152-efe4f080-9278-11e9-8ce8-7c6e8fd9e167.png">

Then look inside of the frameworks folder for the RNRadar project:

<img width="268" alt="Screen Shot 2019-06-19 at 9 58 08 AM" src="https://user-images.githubusercontent.com/9150/59785154-efe4f080-9278-11e9-8a69-6fa544a139d4.png">

By removing the test target OCMock will no longer attempt to compile. And by removing the frameworks linked inside of the project, which are not present unless you install them internally via Carthage, the library will use the CocoaPods installed frameworks.

The library author should be able to resolve this hangup pretty easily. Hopefully they can get a small update out. Until then you may have to do this manually as I have.

**Comment by russellcullen** [comment]
Thanks for the report and the workaround @jimjeffers !

We'd happily take a look at a pull request if you have a quick fix handy, keep in mind we can't simply remove the test target as we need to run tests. 

We're actively working on a solution and apologize for the inconvenience here, will keep this issue open until a fix is released.

**Comment by andersonqi** [comment]
@jimjeffers I used the same way to solve it at the time. Thanks for the help

**Comment by jimjeffers** [comment]
@russellcullen that makes sense. I do not have a PR as I've never made my own RN package for distribution. But I can say looking at all of the other dependent libs in the project... none of them include any native test code. So there must be an alternative way to handle this. My guess is you want to create a build script that removes the linked frameworks and the test/test targets from the release build. Wish I had a solution to have the best of both worlds. For now you may just want to update the readme w/ a few extra steps for iOS.
