### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by thomaslc66** [radarlabs/react-native-radar#81]
I think this library needs a full exemple and some update on explainations. The library is not well introduced and the class or small exemple on the website are not complete.

Was having real issues diggin into it

**Comment by russellcullen** [comment]
Hey @thomaslc66 thanks for your suggestion. What in particular are you having issues with that could use more explanation, always happy to help!

**Comment by thomaslc66** [comment]
Hey @thomaslc66 thanks... yes, not really understanding the point in calling Radar.trackOnce() for foreground tracking and then Radar.startTracking() for background, as it seems that Radar.trackOnce() is called once and then nothing (on android) as i've read all issues seems like there something with background task, but... even on first call if i log the result i get this:

![image](https://user-images.githubusercontent.com/9827392/59949761-60a42c80-9474-11e9-9cc8-69de3712356f.png)

![image](https://user-images.githubusercontent.com/9827392/59950162-677f6f00-9475-11e9-9182-3f96b71efa7f.png)

An example with a map would be great as the the class example on the website is not working as it's missing a render method. I can't see the result JSON array so maybe a example of a full response could help (me and other people)

**Comment by russellcullen** [comment]
Yes `Radar.trackOnce()` works exactly as you described: syncs a singular location with Radar and then delivers the result. `Radar.startTracking()` is used to start background persistent tracking to enabled background event generation. You can learn more about the differences here https://radar.io/documentation/sdk#ios-foreground and https://radar.io/documentation/sdk#ios-background

> [...] as the the class example on the website is not working as it's missing a render method [...]
To what class are you referring? Apologies on the inconvenience here, we want to make sure our docs are up to date and working if that's not the case. 

We're working on getting more complete docs and example code in the future, an example with a map is a great idea.

**Comment by nickpatrick** [comment]
Hi, docs have been updated and moved onto our main docs site: https://radar.io/documentation/sdk/react-native
