### ISSUE TITLE
Add support for auto-linking native modules (React Native 0.60+)

### ISSUE THREAD

**Issue by alexgsummer** [radarlabs/react-native-radar#84]
**Is your feature request related to a problem? Please describe.**
Auto-linking the native modules can simplify the installation steps.

**Describe the solution you'd like**
React Native has introduced [auto-linking native modules](https://facebook.github.io/react-native/blog/2019/07/03/version-60#native-modules-are-now-autolinked) with version 0.60. Documentation will need to be updated for those using React Native < 0.60 and those on 0.60+.

**Describe alternatives you've considered**
The existing `react-native link react-native-radar` can still be used.

**Comment by nickpatrick** [comment]
Hi, https://github.com/radarlabs/react-native-radar/releases/tag/3.0.0 upgrades to React Native 0.60 and adds support for autolinking.
