### ISSUE TITLE
No linking resources on generating APK

### ISSUE THREAD

**Issue by mateusschenattoongo** [radarlabs/react-native-radar#88]
**Describe the bug**
When I run "./gradlew assembleRelease" the gradlew show me a error on build.
com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

**To Reproduce**
1 - cd android
2 - ./gradlew assembleRelease

**Screenshots**
![image](https://user-images.githubusercontent.com/55811673/70739662-1e0e2f00-1cf6-11ea-86bd-64cd9cba76f3.png)

**Metadata (please complete the following information):**
 - React Native Radar Version: ^2.1.9
 - React Native Version: 0.60.5
 - Platform: Android

**Comment by nickpatrick** [comment]
Hi, can you please try again on the latest version?
