### ISSUE TITLE
No user geofences is returned in Radar.trackOnce()

### ISSUE THREAD

**Issue by ajisamie** [radarlabs/react-native-radar#89]
Hi, I am able to implement radar and track user location in foreground using Radar.trackOnce and it returns success. However I want to be able to get the geofences the user is in at the same time, but user.getGeofences() in the onComplete method returns an empty list of geofences, even if the user is in one.

Please I need help solving this. Thanks in advance

**Comment by nickpatrick** [comment]
Hi, are you checking `user.geofences` or `user.getGeofences()`? Should be `user.geofences`.

Have you confirmed in the Radar dashboard that the user is inside the geofences? (1) Call `Radar.trackOnce()`, (2) find user in Radar dashboard, (3) verify that user timestamp is current and user is inside geofences.

**Comment by ajisamie** [comment]
Sorry this question is supposed to be under Android. And I used user.getGeofences() following the sample app. I’m developing for Android 

In the dashboard I’m able to see the user and the time stamp and see that the user is in the area I created the geofence but the “entered geofences” event isn’t triggered

**Comment by nickpatrick** [comment]
Keep in mind that the event will only trigger the first time the user enters the geofence. To trigger another event, the user will need to exit the geofence (which will generate an exit event) and then re-enter the geofence.

**Comment by ajisamie** [comment]
I see. Because it was triggered just once. But then I deleted the previous geofence and added additional geofences and tried again but it could not see them.

Does that mean the user has to exit the area completely and enter again before the event will be triggered for the new geofences?
